# Numpy
![](https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/330px-NumPy_logo_2020.svg.png)

학습 목표

- Numpy 배열의 기본 개념을 이해합니다.
- 1차원, 2차원, 3차원 배열을 만들 수 있습니다.
- Reshape 기능을 사용해 배열 형태를 바꿀 수 있습니다.
- 인덱싱과 슬라이싱으로 원하는 데이터를 조회할 수 있습니다.
- 배열 사이의 기본적인 연산을 수행할 수 있습니다.

## 1.라이브러리 불러오기

- Numpy 배열을 사용하려면 우선 **numpy** 라이브러리를 불러와야 합니다.
- numpy 라이브러리는 일반적으로 **np** 별칭을 붙여 불러옵니다.

In [ ]:
# 라이브러리 불러오기
import numpy as np

### [참고] 왜 배열?

**문제1**: 다음 리스트 각 요소에 2를 곱하세요.

In [ ]:
# 리스트
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# 2 곱하기? 
a = a * 2

# 확인
print(a)

**문제2**: 다음 리스트 요소 중에서 짝수만 표시하세요.

In [ ]:
# 리스트
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# 짝수만 표시...몰라요ㅜ.ㅜ

**문제3**: 다음 배열 각 요소에 2를 곱하세요.

In [ ]:
# 배열
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# 확인
print(a)

# 2 곱하기
a = a * 2

# 확인
print(a)

**문제4**: 다음 배열 요소 중에서 짝수만 표시하세요.

In [ ]:
# 배열
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# 확인
print(a)

# 짝수만 표시
print(a[a % 2 == 0])

## 2.배열 만들기

- 편의를 위해 **Numpy 배열**을 그냥 **배열**이라고 부르기로 합시다.
- 이후 데이터 처리시 배열로 변환해 연산을 하거나, 결과가 배열로 표시되는 경우가 있습니다.
- 배열에 대한 개념은 정확히 파악해 두기를 권고합니다.

### 2.1.용어 정의

<img src='https://raw.githubusercontent.com/Jangrae/img/master/array.png' width=300 align="left"/>

**[용어]**
- axis: 배열의 각 축
- rank: 축의 개수
- shape: 축의 길이, 배열의 크기

  
**[3 x 4 배열의 경우]**
- axis 0 과 axis 1 을 갖는 2차원 배열
- rank 2 array 
- shape는 (3, 4)

### 2.2.배열 만들기

- **np.array() 함수**를 사용해서 배열을 만듭니다.
- 대부분 **리스트**로부터 배열을 만들거나, 머신러닝 관련 함수 결괏값이 배열이 됩니다.

#### 2.2.1.배열 만들기

**1) 1차원 배열 만들기**

In [ ]:
# 1차원 리스트
a1 = [1, 2, 3, 4, 5]

# 배열로 변환
b1 = np.array(a1)

# 확인
print(b1)

**2) 2차원 배열 만들기**

In [ ]:
# 2차원 리스트 
# a2 = [[1.5, 2.5, 3.2], [4.2, 5.7, 6.4]]
a2 = [[1.5, 2.5, 3.2], 
      [4.2, 5.7, 6.4]]

# 배열로 변환
b2 = np.array(a2)

# 확인
print(b2)

**3) 3차원 배열 만들기**

In [ ]:
# 3차원 리스트
# a3 = [[[1, 3, 1], [4, 7, 6], [8, 3, 4]], [[6, 2, 4], [8, 1, 5], [3, 5, 9]]]
a3 = [[[1, 3, 1],
       [4, 7, 6],
       [8, 3, 4]],
      [[6, 2, 4],  
       [8, 1, 5],
       [3, 5, 9]]]

# 배열로 변환
b3 = np.array(a3)

# 확인
print(b3)

#### 2.2.2.배열 정보 확인

- 배열 정보를 확인하는 다음 속성들을 기억하시기 바랍니다.
- 특히 shape 속성은 이후에도 많이 사용될 것입니다.

<img src='https://github.com/DA4BAM/image/blob/main/1,2,3%20%EC%B0%A8%EC%9B%90.png?raw=true' width=800 align="left"/>

**1) 차원 확인**

- ndim 속성으로 배열 차원을 확인합니다.

In [ ]:
# 차원 확인
print(b1.ndim)
print(b2.ndim)
print(b3.ndim)

**2) 형태(크기) 확인**

- shape 속성으로 배열 형태를 확인합니다.
- 결과는 다음과 같은 형태의 튜플로 표시됩니다.
    - 1차원: (x, )
    - 2차원: (x, y)
    - 3차원: (x, y, z)
- 앞에서 부터 axis 0, axis 1, axis 2의 크기를 의미합니다.

In [ ]:
# 형태(크기) 확인
print(b1.shape) 
print(b2.shape) 
print(b3.shape)

**3) 요소 자료형 확인**

- dtype 속성으로 배열에 포함된 요소들의 자료형을 확인합니다.
- 배열은 한 가지 자료형만 가질 수 있다는 특징이 있습니다.

In [ ]:
# 요소 자료형 형식 확인
print(b1.dtype)
print(b2.dtype)
print(b3.dtype)

<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

[문1] numpy 라이브러리를 np 별칭을 주어 불러오세요.

In [ ]:
# 라이브러리 불러오기
import numpy as np

[문2] 다음에 주어진 데이터를 갖는 1차원 배열을 만든 후 ndim, shape, dtype을 확인해 보세요.

In [ ]:
# 10, 11, 12, 13, 14, 15

# 배열 만들기
arr = np.array([10, 11, 12, 13, 14, 15])

# 확인
print(arr)

# 정보 확인
print(arr.ndim)
print(arr.shape)
print(arr.dtype)

[문3] 다음에 주어진 리스트를 요소로 갖는 2차원 배열을 만든 후 ndim, shape, dtype을 확인해 보세요

In [ ]:
a = [[11, 12, 13, 14], [15, 16, 17, 18], [19, 20, 21, 22]]

# 배열 만들기
arr = np.array(a)

# 확인
print(arr)

# 정보 확인
print(arr.ndim)
print(arr.shape)
print(arr.dtype)

#### 2.2.3.Reshape

- 배열을 사용할 때 다양한 형태(Shape)로 변환할 필요가 있습니다.
- 배열에 포함된 **요소가 사라지지 않는 형태**라면 자유롭게 변환할 수 있습니다.
- (3, 4) → (2, 6) → (4, 3) → (12, 1) → (6, 2) 등등 요소 개수만 변하지 않으면 됩니다.

In [ ]:
# (2, 3) 형태의 2차원 배열 만들기
a = np.array([[1, 2, 3], 
              [4, 5, 6]])

# 확인
print(a)

**1) (2, 3) → (3, 2)**

In [ ]:
# (3, 2) 형태의 2차원 배열로 Reshape
b = a.reshape(3, 2)

# 확인
print(b)

**2) (2, 3) → (6,)**

In [ ]:
# 1차원 배열로 Reshape
# c = a.reshape(6,)
c = a.reshape(6)

# 확인
print(c)

**3) -1의 편리성**

- **(*m*, -1)** 또는 **(-1, *n*)** 처럼 사용해 행 또는 열 크기 한 쪽만 지정할 수 있습니다.

In [ ]:
# (2, 3) 형태의 2차원 배열 만들기
a = np.array([[1, 2, 3], 
              [4, 5, 6]])

# 확인
print(a)

In [ ]:
# reshape(m, -1) 형태로 지정하여 Reshape 가능
print(a.reshape(1, -1))
print()

print(a.reshape(2, -1))
print()

print(a.reshape(3, -1))
print()

#print(a.reshape(4, -1))
#print(a.reshape(5, -1))

print(a.reshape(6, -1))

<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

[문1] 다음에 주어진 배열의 형태(shape)를 확인한 후 요구되는 형태로 바꿔 보세요.

In [ ]:
# 배열 만들기
a = np.array([[11, 12, 13, 14], 
              [15, 16, 17, 18], 
              [19, 20, 21, 22]])

# 배열 형태 확인
print(a.shape)

# (4, ?))형태의 2차원 배열
a1 = a.reshape(4, -1)

# 확인
print(a1)

# (2, ?) 형태의 2차원 배열
a2 = a.reshape(2, -1)

# 확인
print(a2)

## 3.배열 인덱싱과 슬라이싱

- 지금까지 다룬 자료형들 보다 배열 인덱싱과 슬라이싱이 조금 어렵습니다.

### 3.1.인덱싱

- 1차원 배열은 리스트와 방법이 같으므로 설명을 생략합니다.
- **배열[행, 열]** 형태로 특정 위치의 요소를 조회합니다.
- **배열[[행1,행2,..], :]** 또는 **배열[[행1,행2,..]]** 형태로 특정 행을 조회합니다.
- **배열[:, [열1,열2,...]]** 형태로 특정 열을 조회합니다.
- **배열[[행1,행2,...], [열1,열2,...]]** 형태로 특정 행의 특정 열을 조회합니다.

<img src='https://github.com/DA4BAM/image/blob/main/%EB%B0%B0%EC%97%B4%20%EC%8A%AC%EB%9D%BC%EC%9D%B4%EC%8B%B1.png?raw=true' width=800 align="left"/>

In [ ]:
# (3, 3) 형태의 2차원 배열 만들기
a = np.array([[1, 2, 3],
              [4, 5, 6], 
              [7, 8, 9]])

# 확인
print(a)

**1) 요소 조회**

In [ ]:
# 첫 번째 행, 두 번째 열 요소 조회
print(a[0, 1])

**2) 행 조회**

In [ ]:
# 첫 번째, 두 번째 행 조회
# print(a[[0, 1], :])
print(a[[0, 1]])

In [ ]:
# 첫 번째, 두 번째, 세 번째 행 조회
# print(a[[0, 1, 2], :])
print(a[[0, 1, 2]])

**3) 열 조회**

In [ ]:
# 첫 번째, 두 번째 열 조회
print(a[:, [0, 1]])

**4) 행, 열 조회**

In [ ]:
# 배열 확인
print(a)

In [ ]:
# 두 번째 행 두 번째 열의 요소 조회
print(a[[1], [1]])

In [ ]:
# 세 번째 행 두 번째 열의 요소 조회
print(a[[2], [1]])

In [ ]:
# 첫 번째 행 첫 번째 열, 두 번째 행 두 번째 열의 요소 조회
print(a[[0, 1], [0, 1]])

In [ ]:
# 첫 전째 행 첫 번째 열, 두 번째 행 두 번째 열, 세 번째 행 첫 번째 열의 요소 조회
print(a[[0, 1, 2], [0, 1, 0]])

<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

주어진 배열을 이용하여 다음 결과를 얻도록 문제를 푸시오.

In [ ]:
a = np.array([[11, 12, 13, 14], 
              [15, 16, 17, 18], 
              [19, 20, 21, 22]])

[문1] 16

In [ ]:
a[1,1]

[문2] [19 20 21 22]

In [ ]:
a[2]

[문3] [13  17  21]

In [ ]:
a[:,2]

[문4] [16  22]

In [ ]:
a[[1,2],[1,3]]

### 3.2.슬라이싱

- **배열[행1:행N,열1:열N]** 형태로 지정해 그 위치의 요소를 조회합니다.
- 조회 결과는 **2차원 배열**이 됩니다.
- 마지막 **범위 값은 대상에 포함되지 않습니다.**
- 즉, **배열[1:M, 2:N]**이라면 1 ~ M-1행, 2 ~ N-1열이 조회 대상이 됩니다.

<img src='https://github.com/DA4BAM/image/blob/main/%EB%B0%B0%EC%97%B4%20%EC%8A%AC%EB%9D%BC%EC%9D%B4%EC%8B%B12.png?raw=true' width=800 align="left"/>

In [ ]:
# (3, 3) 형태의 2차원 배열 만들기
a = np.array([[1, 2, 3],
              [4, 5, 6], 
              [7, 8, 9]])

# 확인
print(a)

In [ ]:
# 첫 번째 ~ 두 번째 행 조회
# print(a[0:2, :])
print(a[0:2])

In [ ]:
# 첫 번째 행, 첫 번째 ~ 두 번째 열 조회
print(a[0, 0:2])

In [ ]:
# 첫 번째 ~ 세 번째 행, 두 번째 ~ 세 번째 열 조회
print(a[0:3, 1:3])

In [ ]:
# 두 번째 ~ 끝 행, 두 번째 ~ 끝 열 조회
print(a[1:, 1:])

<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

주어진 배열을 이용하여 다음 결과를 얻도록 문제를 푸시오.

In [ ]:
a = np.array([[11, 12, 13, 14], 
              [15, 16, 17, 18], 
              [19, 20, 21, 22]])

[문1]   

[[12  
16  
20]

In [ ]:
a[:,1:2]

[문2] 

[[16  17  
 20  21]]

In [ ]:
a[1:, 1:3]

### 3.3.조건 조회

- **조건에 맞는 요소를 선택**하는 방식이며, **불리안 방식**이라고 부릅니다.
- 조회 결과는 **1차원 배열**이 됩니다.

In [ ]:
# 2차원 배열 만들기
score= np.array([[78, 91, 84, 89, 93, 65],
                 [82, 87, 96, 79, 91, 73]])

# 확인
print(score)

- **배열[조건]** 형태로 해당 조건에 맞는 요소만 조회합니다.

In [ ]:
# 요소 중에서 90 이상인 것만 조회
print(score[score >= 90])

- 검색 조건을 변수로 선언해 사용할 수 있습니다.

In [ ]:
# 요소 중에서 90 이상인 것만 조회
condition = score >= 90
print(score[condition])

- 여러 조건을 **&** 와 **|** 로 연결하여 조회할 수 있습니다.

In [ ]:
# 모든 요소 중에서 90 이상 95 미만인 것만 조회
print(score[(score >= 90) & (score <= 95)])

<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align = "left"/>

[문1] 다음 배열에서 80 미만의 데이터만 추출하시오.

In [ ]:
# 2차원 배열 만들기
score= np.array([[78, 91, 84, 89, 93, 65],
                 [82, 87, 96, 79, 91, 73]])

# 확인
print(score)

# 짝수만 조회
print(score[score <80 ])

[문2] 다음 배열에서 짝수만 추출해 보세요.

In [ ]:
# 2차원 배열 만들기
score= np.array([[78, 91, 84, 89, 93, 65],
                 [82, 87, 96, 79, 91, 73]])

# 확인
print(score)

# 짝수만 조회
print(score[score % 2 == 0])

## 4.배열 연산

- 배열 사이의 더하기, 빼기, 곱하기, 나누기 등은 이해하기 쉽습니다.
- 하지만 행렬 곱, 행렬 합등의 연산은 악갼의 수학적 지식이 필요합니다.
- 행렬 연산은 선형 대수를 위한 것이므로 설명을 생략합니다.

<img src='https://github.com/DA4BAM/image/blob/main/%EB%B0%B0%EC%97%B4%EC%97%B0%EC%82%B0.png?raw=true' width=600 align="left"/>

In [ ]:
# 두 개의 (2, 2) 형태의 2차원 배열 만들기
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

# 확인
print(x)
print(y)

**1) 배열 더하기**

- \+ 또는 **np.add()** 함수를 사용합니다.

In [ ]:
# 배열 더하기
print(x + y)

# 또는
print(np.add(x, y))

**2) 배열 뺴기**

- \- 또는 **np.subtract()** 함수를 사용합니다.

In [ ]:
# 배열 빼기
print(x - y)

# 또는
print(np.subtract(x, y))

**3) 배열 곱하기**

- \* 또는 **np.multiply()** 함수를 사용합니다.

In [ ]:
# 배열 곱하기
print(x * y)

# 또는
print(np.multiply(x, y))

**4) 배열 나누기**

- \/ 또는 **np.divide()** 함수를 사용합니다.

In [ ]:
# 배열 나누기
print(x / y)

# 또는
print(np.divide(x, y))

**5) 배열 제곱**

- \** 또는 **np.power()** 함수를 사용합니다.

In [ ]:
# 배열 y 제곱
print(x ** y)

# 또는
print(np.power(x, y))

In [ ]:
# 배열 제곱
print(x ** 2)

**6) 배열 집계**

- np.sum(), 혹은 array.sum()
    * axis = 0 : 열 기준 집계
    * axis = 1 : 행 기준 집계
    * 생략하면 : 전체 집계
- 동일한 형태로 사용 가능한 함수 : np.max(), np.min, np.mean(), np.std()

In [ ]:
# array를 생성합니다.
a = np.array([[1,5,7],[2,3,8]])
print(a)

In [ ]:
# 전체 집계
print(np.sum(a))

# 열기준 집계
print(np.sum(a, axis = 0))

# 행기준 집계
print(np.sum(a, axis = 1))

* 추가로, np.argmax(), np.argmin() 도 있습니다.

<img src='https://github.com/DA4BAM/image/blob/main/%EB%B0%B0%EC%97%B4_argmin.png?raw=true' width=800 align="left"/>

In [ ]:
print(a)
# 전체 중에서 가장 큰 값의 인덱스
print(np.argmax(a))

# 행 방향 최대값의 인덱스
print(np.argmax(a, axis = 0))

# 열 방향 최대값의 인덱스
print(np.argmax(a, axis = 1))

## 5.종합실습

1) numpy 라이브러리를 np 별칭을 주어 불러오세요.

In [ ]:
# 라이브러리 불러오기
import numpy as np

2) 다음 형태를 갖는 2차원 배열을 만들어 np_arr 변수로 선언하세요.

In [ ]:
# [[  1  2  3]
#  [  4  5  6]
#  [  7  8  9]
#  [ 10 11 12]]

# 배열 만들기
np_arr = np.array([[  1,  2,  3],
                   [  4,  5,  6],
                   [  7,  8,  9],
                   [ 10, 11, 12]])

# 확인
print(np_arr)

3) shape 속성을 사용해 np_arr 배열의 행과 열의 크기를 확인하세요.

In [ ]:
# 배열 크기 확인
np_arr.shape

4) np_arr 배열을 아래 주어진 3 X 4 형태의 배열로 바꿔서 np_02 배열로 선언하고 확인하세요.

In [ ]:
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

# 형태 변경
np_02 = np_arr.reshape(3, -1)

# 확인
print(np_02)

5) np_arr 배열의 세 번째 행의 요소들을 조회하세요.

In [ ]:
# [7 8 9] 조회
print(np_arr[2])

6) np_arr 배열의 모든 요소에 10을 곱한 결과를 조회하세요.

In [ ]:
# 10 곱하기
print(np_arr * 10)

7) 아래의 출력문이 어떤 값을 출력할 지 추측한 후에 결과를 확인하세요.  
[ 8  9 10 11 12]

In [ ]:
# 조건 조회
print(np_arr[np_arr > 7])

8) 7번 실습에서 선택된 요소들의 값만 각각 2배로 만드세요.

In [ ]:
# 조회 결과에 대한 연산
np_arr[np_arr > 7] = np_arr[np_arr > 7] * 2

9) np_arr 배열의 값을 조회해서 변경된 내용을 확인해 보세요.

In [ ]:
# 원본 배열 확인
print(np_arr)

10) np_arr 배열의 요소들 중에서 3의 배수는 1, 아니면 0인 배열을 만들고 조회하시오.

In [ ]:
a = np.where(np_arr % 2 == 0, 0, 1)
print(a)

11) np_arr의 전체 평균, 열별 평균, 행별 평균을 구하세요.

In [ ]:
print(np_arr)
print('-'* 50)
print(np.mean(np_arr))
print('-'* 50)
print(np.mean(np_arr, axis = 0))
print('-'* 50)
print(np.mean(np_arr, axis = 1))

----

# Pandas

<img src='https://blog.kakaocdn.net/dn/zy1Or/btqM39h0uLB/fHnntePsHiwAIFStdqGsLk/img.png' width=300 align="left"/>

## 1.데이터프레임 생성

### 1.1.데이터프레임 이해

#### 1.1.1.데이터프레임이란


- Pandas 사용 목적이 데이터프레임을 사용하기 위한 목적으로 봐도 됩니다.
- 데이터를 처리, 조회, 분석하는 가장 효율적인 방법이 데이터프레임을 사용하는 것입니다.
- 일반적으로 접하게 되는 **테이블** 형태, **엑셀** 형태로 생각하시면 됩니다.
- 직접 만들 수 있으나 보통은 **csv 파일**, **엑셀 파일** 또는 DB에서 읽어옵니다.

<img src='https://raw.githubusercontent.com/Jangrae/img/master/dataframe_sample.png' width=800 align="left"/>

#### 1.1.2.데이터프레임 형태

- 데이터프레임은 **인덱스(=행 이름)**와 **열 이름**이 있고 없고에 따라 다른 형태를 갖습니다.
- 인덱스란 행을 지정할 때 사용하는 정보이고, 열 이름은 열을 지정할 때 사용하는 정보입니다.

<img src='https://raw.githubusercontent.com/Jangrae/img/master/dataframe05.png' width=450 align="left"/>

**1) 인덱스와 열 이름이 없는 형태**

- 우선 인덱스와 열 이름이 없는 데이터프레임 형태입니다.
- 열 이름이 없는 데이터프레임은 실무에서는 자주 볼 수 없을 것입니다.

<img src='https://raw.githubusercontent.com/Jangrae/img/master/dataframe01.png' width=380 align="left"/>

**2) 열 이름을 지정한 형태**

- 열 이름만 지정한 데이터프레임 형태입니다.
- 특별히 인덱스를 지정할 필요가 없는 경우가 많으므로 자주 보게 되는 형태입니다.

<img src='https://raw.githubusercontent.com/Jangrae/img/master/dataframe02.png' width=380 align="left"/>

**3) 인덱스와 열 이름을 지정한 형태**

- 인덱스와 열 이름 모두를 지정한 데이터프레임 형태입니다.
- 대부분 주식 시세와 같은 날짜가 인덱스로 지정되는 경우입니다.

<img src='https://raw.githubusercontent.com/Jangrae/img/master/dataframe03.png' width=350 align="left"/>

### 1.2.데이터프레임 직접 만들기

- **pd.DataFrame()** 함수를 사용해 데이터프레임을 직접 만들 수 있습니다.
- 대부분 리스트, 딕셔너리, Numpy 배열로부터 데이터프레임을 만듭니다.
- 데이터프레임을 만들기 위해서는 다음 세 가지를 위한 데이터가 필요합니다.
    - 데이터
    - 열 이름
    - 인덱스 이름
- 열 이름을 지정하지 않으면 **열 번호**에 기반한 정수(0, 1, 2...)가 열 이름이 됩니다.
- 인덱스 이름을 지정하지 않으면 **행 번호**에 기반한 정수(0, 1, 2...)가 인덱스 이름이 됩니다.

#### 1.2.1.라이브러리 불러오기

- 데이터프레임을 사용하기 위해서 pandas 라이브러리를 pd 별칭을 주어 불러옵니다.

In [ ]:
# 라이브러리 불러오기
import pandas as pd

#### 1.2.2.딕셔너리로 만들기

- 딕셔너리로 데이터프레임을 만들면 딕셔너리의 **키**가 **열 이름**이 됩니다.
- 인덱스를 지정하지 않으면 행 번호가 인덱스가 됩니다.

In [ ]:
# 딕셔너리 만들기
dict = {'Name': ['Gildong', 'Sarang', 'Jiemae', 'Yeoin'],
        'Level': ['Gold', 'Bronze', 'Silver', 'Gold'],
        'Score': [56000, 23000, 44000, 52000]}

# 확인
print(dict)

In [ ]:
# 데이터프레임 만들기
df = pd.DataFrame(dict)

# 확인
print(df.head())

### 1.3.CSV파일 읽어오기

- 분석용 데이터는 대부분 파일에서 읽어 가져오니 잘 익혀야 할 기능입니다.
- **read_csv()** 함수를 사용해서 CSV 파일에서 데이터를 읽어옵니다.

**[주요옵션]**
- **usecols** : 불러올 칼럼 지정(칼럼이름을 알고 있어야 함)
- sep: 구분자 지정(기본값 = 콤마)
- header: 헤더가 될 행 번호 지정(기본값 = 0)
- index_col: 인덱스 열 지정(기본값 = False)
- names: 열 이름으로 사용할 문자열 리스트
- skiprows: 처음 몇 줄을 무시할 것인지 지정, 리스트로 지정 가능

**[titanic_simple 데이터 셋 정보]**

- PassengerId : 승객번호
- Survived : 생존여부(1:생존, 0:사망)
- Pclass : 객실등급(1:1등급, 2:2등급, 3:3등급)
- Name : 승객이름
- Sex : 성별(male, female)
- Age : 나이
- Fare : 운임($)
- Embarked : 승선지역(Southhampton, Cherbourg, Queenstown)

In [ ]:
# 데이터 읽어오기
path = 'https://raw.githubusercontent.com/DA4BAM/dataset/master/titanic_simple.csv'
data = pd.read_csv(path)  

# 상위 10행만 확인
data.head(10)

<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

[문1] 아래 주어진 경로의 파일에서 데이터를 읽어와 데이터프레임 temp 만들어 보세요.

- 파일 경로: 'https://raw.githubusercontent.com/DA4BAM/dataset/master/Attrition_simple2.CSV'

**[Attrition 데이터 셋 정보]**

|	구분	|	변수 명	|	내용	|	type	|	비고	|
|	----	|	----	|	----	|	----	|	----	|
|	**Target**	|	**Attrition**	|	이직여부, Yes , No	|	범주	| 1- 이직, 0- 잔류		|
|	feature	|	Age	|	나이	|	숫자	|		|
|	feature	|	DistanceFromHome	|	집-직장 거리	|	숫자	|	마일	|
|	feature	|	EmployNumber	|	사번	|	숫자	| 	|
|	feature	|	Gender	|	성별	|	범주	| Male, Female		|
|	feature	|	JobSatisfaction	|	직무 만족도	|	범주	|	1 Low, 2 Medium, 3 High, 4 Very High	|
|	feature	|	MaritalStatus	|	결혼상태	|	범주	| Single, Married, Divorced		|
|	feature	|	MonthlyIncome	|	월급	|	숫자	| 달러	|
|	feature	|	OverTime	|	야근여부	|	범주	|	Yes, No	|
|	feature	|	PercentSalaryHike	|	전년대비 급여인상율	|	숫자	|	%	|
|	feature	|	TotalWorkingYears	|	총 경력 연수	|	숫자	|		|

In [ ]:
# 데이터 읽어오기
path = 'https://raw.githubusercontent.com/DA4BAM/dataset/master/Attrition_simple2.CSV'
data = pd.read_csv(path)  

# 상위 5개 확인
data.head(5)

[문2] csv file로부터 읽어옵시다.

- 파일 이름 : 'airquality_simple.csv'
- 파일을 home directory로 복사해 넣고 읽어 옵니다.

**[airquality_simple 데이터 셋 정보]**

- Ozone : 오존농도
- Solar.R: 태양복사열
- Wind: 풍속
- Temp: 기온
- Month: 월
- Day: 일

In [ ]:
# 데이터 읽어오기
data = pd.read_csv('airquality_simple.csv')  

# 상위 5개 확인
data.head(5)

## 2.데이터프레임 탐색

- 파일에서 불러온 데이터의 크기, 내용, 분포, 누락된 값 등을 확인할 수 있어야 합니다.
- 확인된 내용을 통해 데이터 전처리 필요 여부를 결정합니다.
- 데이터를 알아야 데이터를 분석할 수 있습니다.

In [ ]:
# 라이브러리 불러오기
import pandas as pd

* Attrition 데이터 불러오기

**[Attrition 데이터 셋 정보]**

|	구분	|	변수 명	|	내용	|	type	|	비고	|
|	----	|	----	|	----	|	----	|	----	|
|	**Target**	|	**Attrition**	|	이직여부, Yes , No	|	범주	| 1- 이직, 0- 잔류		|
|	feature	|	Age	|	나이	|	숫자	|		|
|	feature	|	DistanceFromHome	|	집-직장 거리	|	숫자	|	마일	|
|	feature	|	EmployNumber	|	사번	|	숫자	| 	|
|	feature	|	Gender	|	성별	|	범주	| Male, Female		|
|	feature	|	JobSatisfaction	|	직무 만족도	|	범주	|	1 Low, 2 Medium, 3 High, 4 Very High	|
|	feature	|	MaritalStatus	|	결혼상태	|	범주	| Single, Married, Divorced		|
|	feature	|	MonthlyIncome	|	월급	|	숫자	| 달러	|
|	feature	|	OverTime	|	야근여부	|	범주	|	Yes, No	|
|	feature	|	PercentSalaryHike	|	전년대비 급여인상율	|	숫자	|	%	|
|	feature	|	TotalWorkingYears	|	총 경력 연수	|	숫자	|		|

In [ ]:
# 데이터 읽어오기
path = 'https://raw.githubusercontent.com/DA4BAM/dataset/master/Attrition_simple2.CSV'
data = pd.read_csv(path)  

# 상위 5개 확인
data.head(5)

**[참고] 우선 익숙해져야 할 것들**

- head(): 상위 데이터 확인
- tail(): 하위 데이터 확인
- shape: 데이터프레임 크기
- index: 인덱스 정보 확인
- values: 값 정보 확인
- columns: 열 정보 확인
- dtypes: 열 자료형 확인
- info(): 열에 대한 상세한 정보 확인
- describe(): 기초통계정보 확인

### 2.1.앞, 뒤 일부 데이터, 크기 확인

- **head(*n*), tail(*n*)** 메소드를 사용해 앞 뒤 데이터를 확인합니다.
- 개수를 지정하지 않으면 기본적으로 5개 행이 조회됩니다.

**1) 상위 데이터 확인**

In [ ]:
# 상위 10개 행 데이터
data.head(10)

**2) 하위 데이터 확인**

In [ ]:
# 하위 3개 행 데이터
data.tail(3)

**3) 크기 확인**

- **(rows, cols)** 값을 갖는 **튜플** 형태로 확인이 가능합니다.
- 데이터를 분석할 때 처리할 **데이터 양을 확인**하는 목적으로 많이 사용 합니다.

In [ ]:
# 행 수와 열 수 확인
data.shape

### 2.2.열, 행 정보 보기

**1) 열 확인**

In [ ]:
# 열 확인
print(data.columns)
print(data.columns.values) # np array 형태

In [ ]:
# 데이터프레임을 리스트 함수에 넣으면 열 이름이 리스트로 반환됨.
list(data)

**2) 자료형 확인**
- int64: 정수형 데이터(int)
- float64: 실수형 데이터(float)
- object: 문자열 데이터(string)

In [ ]:
# 열 자료형 확인
data.dtypes

In [ ]:
# 열 자료형, 값 개수 확인
data.info()

**3) 기초통계정보 확인**

- describe() 메소드는 데이터에 대한 많은 정보를 제공하는 매우 중요한 메소드입니다.
- 데이터분석과정에서 자세히 살펴볼 예정이므로 여기서는 **가볍게 실행만** 해봅니다.
- 개수(count), 평균(mean), 표준편차(std), 최솟값(min), 사분위값(25%, 50%, 75%), 최댓값(max)을 표시합니다.

In [ ]:
# 기초통계정보
data.describe()

- 일부 열에 대해서만 기초통계정보를 확인할 수 있습니다.

In [ ]:
# 기초 통계 정보
print(data[['Age', 'MonthlyIncome']].describe())

<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

[문1] 다음 경로의 파일을 읽어와 air 데이터프레임으로 저장하세요.

- 파일 경로: 'https://raw.githubusercontent.com/DA4BAM/dataset/master/airquality_simple.csv'

In [ ]:
# 데이터 읽어오기
path = 'https://raw.githubusercontent.com/DA4BAM/dataset/master/airquality_simple.csv'
air = pd.read_csv(path)

[문2] 데이터프레임 관련 정보를 확인하세요.

In [ ]:
# 상위 데이터 확인
print(air.head())

In [ ]:
# 크기 확인
print(air.shape)

In [ ]:
# 열 이름 확인
print(air.columns)

In [ ]:
# 열 자료형, 값 개수 확인
print(air.info())

In [ ]:
# 기초통계정보 확인
print(air.describe())

### 2.3.정렬해서 보기

- 인덱스를 기준으로 정렬하는 방법과 특정 열을 기준으로 정렬하는 방법이 있습니다.
- **sort_values()** 메소드로 **특정 열**을 기준으로 정렬합니다.
- **ascending** 옵션을 설정해 오름차순, 내림차순을 설정할 수 있습니다.
    - ascending=True: 오름차순 정렬(기본값)
    - ascending=False: 내림차순 정렬

In [ ]:
# 단일 열 정렬
data.sort_values(by='MonthlyIncome', ascending=False)

In [ ]:
# 복합 열 정렬
data.sort_values(by=['JobSatisfaction', 'MonthlyIncome'], ascending=[True, False])

<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

[문1] 다음 경로의 파일을 읽어와 데이터프레임으로 저장하세요.

- 파일 경로: 'https://raw.githubusercontent.com/DA4BAM/dataset/master/airquality_simple.csv'

In [ ]:
# 데이터 읽어오기
path = 'https://raw.githubusercontent.com/DA4BAM/dataset/master/airquality_simple.csv'
air = pd.read_csv(path)
air.head()

[문2] Ozone 열을 기준으로 내림차순 정렬해서 조회하세요.

In [ ]:
# 내림차순 정렬
print(air.sort_values(by='Ozone', ascending=False))

[문3] Temp 열을 기준으로 오름차순 정렬해서 조회하세요.

In [ ]:
# 오름차순 정렬
print(air.sort_values(by='Temp', ascending=True))

[문4] Wind 열을 기준으로 내름차순 정렬해서 상위 10개 행만 조회하세요.

In [ ]:
# 오름차순 정렬
print(air.sort_values(by='Wind', ascending=False).head(10))

### 2.4.기본 집계

- 데이터를 좀더 이해하기 위해 고유값, 합, 평균, 최댓값, 최솟값 등을 확인합니다.

#### 2.4.1.고유값 확인

- 범주형 열(열이 가진 값이 일정한 값인 경우, 성별, 등급 등)인지 확인할 때 사용합니다.

**1) 고유값 확인**

- unique() 메소드로 고유값을 확인하며, 결괏값은 배열 형태가 됩니다.

In [ ]:
# MaritalStatus 열 고유값 확인
print(data['MaritalStatus'].unique())

**2) 고유값과 개수 확인**

- value_counts() 메소드로 고유값과 그 개수를 확인하며, 결괏값은 시리즈 형태가 됩니다.

In [ ]:
# MaritalStatus 열 고유값 개수 확인
print(data['MaritalStatus'].value_counts())

In [ ]:
# PercentSalaryHike 열 고유값 개수 확인
print(data['PercentSalaryHike'].value_counts())

#### 2.4.2.기본 통계 메소드 사용

- 데이터를 1차 집계 한 후 분석을 진행하는 경우가 많으므로 필히 알아두어야 할 내용입니다.
- 이후에 배우는 Groupby 기능에서 같이 사용됩니다.

In [ ]:
# MonthlyIncome 열 합계 조회
print(data['MonthlyIncome'].sum())

In [ ]:
# MonthlyIncome 열 최댓값 조회
print(data['MonthlyIncome'].max())

In [ ]:
# 'Age', 'MonthlyIncome' 열 평균값 확인
print(data[['Age', 'MonthlyIncome']].mean())

In [ ]:
# 'Age', 'MonthlyIncome' 열 중앙값 확인
print(data[['Age', 'MonthlyIncome']].median())

<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

[문1] 다음 경로의 파일을 읽어와 데이터프레임으로 저장하세요.

- 파일 경로: 'https://raw.githubusercontent.com/DA4BAM/dataset/master/airquality_simple.csv'

In [ ]:
# 데이터 읽어오기
path = 'https://raw.githubusercontent.com/DA4BAM/dataset/master/airquality_simple.csv'
air = pd.read_csv(path)
air.head()

[문2] Ozone 최댓값을 확인하세요.

In [ ]:
print(air['Ozone'].max())

[문3] Temp, Wind 최솟값을 확인하세요.

In [ ]:
print(air[[ 'Temp', 'Wind' ]].min())

### 2.5 종합실습

1) pandas 라이브러리를 pd 별칭을 주어 불러오세요.

In [ ]:
# 라이브러리 불러오기
import pandas as pd

2) read_csv() 함수를 사용해 다음 경로의 파일을 불러와 **titanic** 데이터프레임을 만드세요.

- 파일 경로: https://raw.githubusercontent.com/DA4BAM/dataset/master/titanic_simple.csv

**[titanic_simple 데이터 셋 정보]**

- PassengerId : 승객번호
- Survived : 생존여부(1:생존, 0:사망)
- Pclass : 객실등급(1:1등급, 2:2등급, 3:3등급)
- Name : 승객이름
- Sex : 성별(male, female)
- Age : 나이
- Fare : 운임($)
- Embarked : 승선지역(Southhampton, Cherbourg, Queenstown)

In [ ]:
# 파일 읽어오기
titanic = pd.read_csv('https://raw.githubusercontent.com/DA4BAM/dataset/master/titanic_simple.csv')

3) head() 메소드로 상위 10개 행 데이터를 확인하세요.

In [ ]:
# 상위 10행 출력
titanic.head(10)

4) shape 속성을 사용해 행과 열의 개수를 확인하세요.

In [ ]:
# 크기 확인
titanic.shape

5) dtype 속성을 사용해 각 열의 데이터 형식을 확인하세요.

In [ ]:
# 열 데이터 형식 확인
titanic.dtypes

6) info() 메소드를 사용해 각 열의 값 개수와 데이터 형식 등을 한 번에 확인하세요.

In [ ]:
# 열 정보 확인
titanic.info()

7) describe() 함수를 사용해 기초통계정보를 확인하세요.

In [ ]:
# 기초통계정보 확인
titanic.describe()

8) value_counts() 메소드를 사용해 다음 두 열의 고유값과 그 개수를 각각 
확인하세요.

- Embarked
- Pclass

In [ ]:
# 고유값 개수 확인
print(titanic['Embarked'].unique())
print(titanic['Pclass'].unique())

9) Age, Fare 두 열의 최댓값을 한 번에 확인하세요.

In [ ]:
titanic[['Age', 'Fare']].max()

10) Fare 열을 기준으로 내림차순 정렬해서 상위 10개를 조회하세요.

In [ ]:
titanic.sort_values('Fare', ascending=False).head(10)

## 3.데이터프레임 조회

- 보고자 하는 데이터를 즉시 조회할 수 있도록 반복 학습과 실습을 통해 익숙해져야 합니다.
- 데이터프레임을 대상으로 조회하는 방법은 다양합니다.
- 그 중 한 가지 방법을 선택해 일관되게 사용하기를 권고합니다.

In [ ]:
# 라이브러리 불러오기
import pandas as pd

### 3.1.데이터 읽어오기

* Attrition 데이터 불러오기

**[Attrition 데이터 셋 정보]**

|	구분	|	변수 명	|	내용	|	type	|	비고	|
|	----	|	----	|	----	|	----	|	----	|
|	**Target**	|	**Attrition**	|	이직여부, Yes , No	|	범주	| 1- 이직, 0- 잔류		|
|	feature	|	Age	|	나이	|	숫자	|		|
|	feature	|	DistanceFromHome	|	집-직장 거리	|	숫자	|	마일	|
|	feature	|	EmployNumber	|	사번	|	숫자	| 	|
|	feature	|	Gender	|	성별	|	범주	| Male, Female		|
|	feature	|	JobSatisfaction	|	직무 만족도	|	범주	|	1 Low, 2 Medium, 3 High, 4 Very High	|
|	feature	|	MaritalStatus	|	결혼상태	|	범주	| Single, Married, Divorced		|
|	feature	|	MonthlyIncome	|	월급	|	숫자	| 달러	|
|	feature	|	OverTime	|	야근여부	|	범주	|	Yes, No	|
|	feature	|	PercentSalaryHike	|	전년대비 급여인상율	|	숫자	|	%	|
|	feature	|	TotalWorkingYears	|	총 경력 연수	|	숫자	|		|

In [ ]:
# 데이터 읽어오기
path = 'https://raw.githubusercontent.com/DA4BAM/dataset/master/Attrition_simple2.CSV'
data = pd.read_csv(path)  

# 상위 5개 확인
data.head(5)

In [ ]:
# 확인
data.head()

* 시리즈(Series)와 데이터프레임(DataFrame)
    * 데이터프레임 : 2차원 구조
    * 시리즈 : 1차원 구조
        * 데이터프레임에서 열 하나를 띄어 내면 시리즈!

<img src='https://github.com/DA4BAM/image/blob/main/%EC%8B%9C%EB%A6%AC%EC%A6%88,%20%EB%8D%B0%EC%9D%B4%ED%84%B0%ED%94%84%EB%A0%88%EC%9E%84.png?raw=true' width=500 align="left"/>

### 3.2.특정 열 조회

- **df.loc[ : , [열 이름1, 열 이름2,...]]** 형태로 조회할 열 이름을 리스트로 지정합니다.
- 열 부분은 생략할 수 있었지만, **행 부분을 생략할 수는 없습니다.**
- 하지만 **df[[열 이름1, 열 이름2,...]]** 형태로 인덱서를 생략함이 일반적입니다.
- 조회할 열이 하나면 리스트 형태가 아니어도 됩니다.

In [ ]:
# Attrition 열 조회 : 시리즈로 조회
data['Attrition']

In [ ]:
# Attrition 열 조회2 : 시리즈로 조회
data.Attrition

In [ ]:
# Attrition, Age 열 조회 : 데이터프레임으로 조회
# 대괄호 안에 또 대괄호로 읽지 마시고, 대괄호 안에 리스트!!!
data[['Attrition', 'Age' ]]

<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

[문1] data 데이터프레임에 대해 아래 요구사항에 맞는 구문을 작성하고 실행하세요.

In [ ]:
# 상위 5개 행 조회
print(data.head())

In [ ]:
# PercentSalaryHike 열만 조회
print(data['PercentSalaryHike'])

In [ ]:
#  Age, DistanceFromHome, Gender열만 조회
data[['Age', 'DistanceFromHome', 'Gender']]

In [ ]:
# Age, DistanceFromHome, Gender열만 DistanceFromHome 열 기준으로 내림차순 정렬해서 조회
data[['Age', 'DistanceFromHome', 'Gender']].sort_values(by='DistanceFromHome', ascending=False)

### 3.3.조건으로 조회

- **df.loc[조건]** 형태로 조건을 지정해 조건에 만족하는 데이터만 조회할 수 있습니다.
- 우선 조건이 제대로 판단이 되는지 확인한 후 그 **조건을 대 괄호 안에** 넣으면 됩니다.

**1) 단일 조건 조회**

In [ ]:
# 조건절(조건문)의 결과는 True, False
data['DistanceFromHome'] > 10

In [ ]:
# DistanceFromHome 열 값이 10 보다 큰 행 조회
data.loc[data['DistanceFromHome'] > 10]

**2) 여러 조건 조회**

- [ ]안에 조건을 여러개 연결할 때 **and와 or 대신에 &와 |**를 사용해야 합니다.
- 그리고 각 조건들은 **(조건1) & (조건2)** 형태로 **괄호**로 묶어야 합니다.

In [ ]:
# and로 여러 조건 연결
data.loc[(data['DistanceFromHome'] > 10) & (data['JobSatisfaction'] == 4)]

In [ ]:
# or 조건 : |
data.loc[(data['DistanceFromHome'] > 10) | (data['JobSatisfaction'] == 4)]

**3) 편리한 isin(), between() 메소드**

- **isin([값1, 값2,..., 값n])**: 값1 또는 값2 또는...값n인 데이터만 조회합니다.
- 주의 isin(**리스트**) 값들을 리스트 형태로 입력해야 합니다.

In [ ]:
# 값 나열
data.loc[data['JobSatisfaction'].isin([1,4])]

- 위 구문은 다음과 같은 의미를 갖습니다.

In [ ]:
# or 조건
data.loc[(data['JobSatisfaction'] == 1) | (data['JobSatisfaction'] == 4)]

- **between(값1, 값2)**: 값1 ~ 값2까지 범위안의 데이터만 조회합니다.

In [ ]:
# 범위 지정
data.loc[data['Age'].between(25, 30)]

- 위 구문은 다음과 같은 의미를 갖습니다.

In [ ]:
# and 조건
data.loc[(data['Age'] >= 25) & (data['Age'] <= 30)]

**4) 조건을 만족하는 행의 일부 열 조회**

- **df.loc[조건, ['열 이름1', '열 이름2',...]]** 형태로 조회할 열을 리스트로 지정합니다. ==> 2차원, 데이터프레임형태로 조회

In [ ]:
# 조건에 맞는 하나의 열 조회
data.loc[data['MonthlyIncome'] >= 10000, ['Age']]

In [ ]:
# 조건에 맞는 여러 열 조회
data.loc[data['MonthlyIncome'] >= 10000, ['Age', 'MaritalStatus', 'TotalWorkingYears']]

### 3.4 종합실습

1) pandas 라이브러리를 pd 별칭을 주어 불러오세요.

In [ ]:
# 라이브러리 불러오기
import pandas as pd

2) read_csv() 함수를 사용해 다음 경로의 파일을 불러와 **titanic** 데이터프레임을 만드세요.

- 파일 경로: 'https://raw.githubusercontent.com/DA4BAM/dataset/master/titanic_simple.csv'

**[titanic_simple 데이터 셋 정보]**

- PassengerId : 승객번호
- Survived : 생존여부(1:생존, 0:사망)
- Pclass : 객실등급(1:1등급, 2:2등급, 3:3등급)
- Name : 승객이름
- Sex : 성별(male, female)
- Age : 나이
- Fare : 운임($)
- Embarked : 승선지역(Southhampton, Cherbourg, Queenstown)

In [ ]:
# 파일 읽어오기
titanic = pd.read_csv('https://raw.githubusercontent.com/DA4BAM/dataset/master/titanic_simple.csv')

3) Name 열만 조회하세요.

In [ ]:
titanic['Name']

4) Name, Age, Sex 열만 조회하세요.

In [ ]:
titanic[['Name', 'Age', 'Sex']]

5) Name, Age, Sex 열의 상위 10개 행만 확인하세요.

In [ ]:
titanic[['Name', 'Age', 'Sex']].head(10)

6) 나이가 70세 이상인 탑승객을 조회하시오.

In [ ]:
titanic.loc[titanic['Age']>= 70]

7) Fare(운임)의 평균을 Fare_mean으로 저장하고 그 값을 확인하세요.

In [ ]:
# gre 평균
Fare_mean = titanic['Fare'].mean()

# 확인
print(Fare_mean)

8) 평균 운임보다 적게 내고 탑승한 승객을 조회하시오.

In [ ]:
titanic.loc[titanic['Fare'] < Fare_mean]

9) 승선지역(Embarked)이 'Southhampton', 'Queenstown' 인 승객을 조회하시오.

In [ ]:
titanic.loc[titanic['Embarked'].isin(['Southhampton', 'Queenstown'])]

10) 나이(Age)가 10대(10이상, 20 미만)인 남자 청소년의 평균 운임(Fare)을 구해 봅시다.

In [ ]:
titanic.loc[(titanic['Age']>= 10) & (titanic['Age'] < 20) & (titanic['Sex'] == 'male'), 'Fare' ].mean()

titanic.loc[titanic['Age'].between(10,19.999) & (titanic['Sex'] == 'male'), 'Fare' ].mean()

## 4.데이터프레임 집계

- 상세 데이터가 아닌 집계된 데이터에 대한 분석을 자주 요구하니 익숙해져야 할 내용입니다.
- sum(), mean(), max(), min(), count() 메소드를 사용해 지정한 열 또는 열들을 기준으로 집계합니다.
- 평균을 구하는 메소드가 avg()가 아닌 mean() 임을 주의하기 바랍니다.

In [ ]:
# 라이브러리 불러오기
import pandas as pd

* Attrition 데이터 불러오기

**[Attrition 데이터 셋 정보]**

|	구분	|	변수 명	|	내용	|	type	|	비고	|
|	----	|	----	|	----	|	----	|	----	|
|	**Target**	|	**Attrition**	|	이직여부, Yes , No	|	범주	| 1- 이직, 0- 잔류		|
|	feature	|	Age	|	나이	|	숫자	|		|
|	feature	|	DistanceFromHome	|	집-직장 거리	|	숫자	|	마일	|
|	feature	|	EmployNumber	|	사번	|	숫자	| 	|
|	feature	|	Gender	|	성별	|	범주	| Male, Female		|
|	feature	|	JobSatisfaction	|	직무 만족도	|	범주	|	1 Low, 2 Medium, 3 High, 4 Very High	|
|	feature	|	MaritalStatus	|	결혼상태	|	범주	| Single, Married, Divorced		|
|	feature	|	MonthlyIncome	|	월급	|	숫자	| 달러	|
|	feature	|	OverTime	|	야근여부	|	범주	|	Yes, No	|
|	feature	|	PercentSalaryHike	|	전년대비 급여인상율	|	숫자	|	%	|
|	feature	|	TotalWorkingYears	|	총 경력 연수	|	숫자	|		|

In [ ]:
# 데이터 읽어오기
path = 'https://raw.githubusercontent.com/DA4BAM/dataset/master/Attrition_simple2.CSV'
data = pd.read_csv(path)  

# 상위 5개 확인
data.head(5)

### 4.1 열 하나 집계

- 우선 특정 열의 값 합은 다음과 같이 구할 수 있습니다.

In [ ]:
# MonthlyIncome 합계
data['MonthlyIncome'].sum()

In [ ]:
# MonthlyIncome, TotalWorkingYears 각각의 평균
data[['MonthlyIncome', 'TotalWorkingYears']].mean()

**1) 집계하기**

- 만일 day 별로 합을 구하고자 한다면 다음과 같이 합니다.
- 아래 결과 값 네 개를 더하면 전체 합이 됩니다.
- **as_index=True**를 설정(기본값)하면 집계 기준이 되는 열이 인덱스 열이 됩니다.
- 집계 결과가 data 열만 가지니 **시리즈**가 됩니다.

In [ ]:
# MaritalStatus 별 Age 평균 --> 시리즈
data.groupby('MaritalStatus', as_index=True)['Age'].mean()

- **[['data']].sum()**과 같이 하면 열이 여럿이라는 의미여서 결과가 **데이터프레임**이 됩니다.

In [ ]:
# MaritalStatus 별 Age 평균 --> 데이터프레임
data.groupby('MaritalStatus', as_index=True)[['Age']].mean()

- **as_index=False**를 설정하면 행 번호를 기반으로 한 정수 값이 인덱스로 설정됩니다.

In [ ]:
# MaritalStatus 별 Age 평균 --> 데이터프레임
data.groupby('MaritalStatus', as_index=False)[['Age']].mean()

**2) 데이터프레임으로 선언**

- 집계 결과를 새로운 데이터프레임으로 선언하여 사용하는 경우가 많습니다.
- 집계된 결과를 반복해서 사용하거나, 분석 대상이 되는 경우 데이터프레임으로 선언함이 유익합니다.

In [ ]:
data_mean = data.groupby('MaritalStatus', as_index=False)[['Age']].mean()

# 확인
data_mean

### 4.2 여러 열 집계

- 여러 열에 대한 집계를 같이 할 수 있습니다.
- **[ ['feature1', 'feature2'] ].sum()** 형태와 같이 집계 대상 열을 리스트로 지정합니다.

In [ ]:
data_mean = data.groupby('MaritalStatus', as_index=False)[['Age','MonthlyIncome']].mean()

# 확인
data_mean

- sum() 메소드 앞에 아무 열도 지정하지 않으면 **기준열 이외의 모든 열에 대한 집계**가 수행됩니다.

In [ ]:
data_sum = data.groupby('MaritalStatus', as_index=False).sum()

# 확인
data_sum

- **by=['feature1', 'feature2']** 과 같이 집계 기준 열을 여럿 설정할 수도 있습니다.

In [ ]:
# 'MaritalStatus', 'Gender'별 나머지 열들 평균 조회
data_sum = data.groupby(['MaritalStatus', 'Gender'], as_index=False)[['Age','MonthlyIncome']].mean()

# 확인
data_sum

### 4.3 여러 함수로 한꺼번에 집계

* df.groupby(  )**.agg(['함수1','함수2', ...])**

In [ ]:
data_agg = data.groupby('MaritalStatus', as_index=False)[['MonthlyIncome']].agg(['min','max','mean'])
# 확인
data_agg

<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

[문1] 데이터를 불러와 데이터프레임으로 저장합니다.

- 파일 경로 : https://raw.githubusercontent.com/DA4BAM/dataset/master/airquality_simple.csv

**[airquality_simple 데이터 셋 정보]**

- Ozone : 오존농도
- Solar.R: 태양복사열
- Wind: 풍속
- Temp: 기온
- Month: 월
- Day: 일

In [ ]:
# 데이터 읽어오기
temp = pd.read_csv('https://raw.githubusercontent.com/DA4BAM/dataset/master/airquality_simple.csv')  

# 상위 5개 확인
temp.head(5)

[문2] 월별 Ozone, Wind, Temp 평균을 구해 봅시다.

In [ ]:
temp.groupby('Month', as_index = False)[['Ozone', 'Wind','Temp' ]].mean()

[문3] 월별 Ozone, Wind, Temp에 대해 최대, 최소, 평균, 표준편차 값을 구해 봅시다.

In [ ]:
temp.groupby('Month', as_index = False)[['Ozone', 'Wind','Temp' ]].agg(['max', 'min', 'mean', 'std'])

### 4.3 종합실습

1) pandas 라이브러리를 pd 별칭을 주어 불러오세요.

In [ ]:
# 라이브러리 불러오기
import pandas as pd

2) read_csv() 함수를 사용해 다음 경로의 파일을 불러와 **titanic** 데이터프레임을 만드세요.

- 파일 경로: 'https://raw.githubusercontent.com/DA4BAM/dataset/master/titanic_simple.csv'

**[titanic_simple 데이터 셋 정보]**

- PassengerId : 승객번호
- Survived : 생존여부(1:생존, 0:사망)
- Pclass : 객실등급(1:1등급, 2:2등급, 3:3등급)
- Name : 승객이름
- Sex : 성별(male, female)
- Age : 나이
- Fare : 운임($)
- Embarked : 승선지역(Southhampton, Cherbourg, Queenstown)

In [ ]:
# 파일 읽어오기
titanic = pd.read_csv('https://raw.githubusercontent.com/DA4BAM/dataset/master/titanic_simple.csv')

3) Fare의 중앙값을 확인해 봅시다.

In [ ]:
titanic.Fare.median()

4) 승선지역(Embarked)별 평균 운임(Fare)을 구해 봅시다.

In [ ]:
titanic.groupby('Embarked', as_index = False)['Fare'].mean()

5) 승선지역(Embarked)별, 성별(Sex)별 평균 운임(Fare)과 평균 나이(Age)를 tmp에 저장하고 조회하시오.

In [ ]:
tmp = titanic.groupby(['Embarked','Sex'], as_index = False)['Fare','Age'].mean()

tmp

6) 5번의 결과로 부터 파악할 수 있는 내용은 무엇인가요?

7) 객실등급(Pclass)별, 생존여부(Survived)별 나이(Age), 운임(Fare)의 최대, 최소, 평균, 표준편차를 tmp에 저장하고 조회하시오.

In [ ]:
tmp = titanic.groupby(['Pclass','Survived'], as_index = False)[['Age','Fare']].agg(['max', 'min', 'mean', 'std'])

tmp

## 5.데이터프레임 변경 (1)

- 데이터 전처리를 위해 꼭 익혀두어야 할 내용입니다.
- 반복 학습과 실습을 통해서 익숙해져야 합니다.

In [ ]:
# 라이브러리 불러오기
import pandas as pd
import numpy as np

* Attrition 데이터 불러오기

**[Attrition 데이터 셋 정보]**

|	구분	|	변수 명	|	내용	|	type	|	비고	|
|	----	|	----	|	----	|	----	|	----	|
|	**Target**	|	**Attrition**	|	이직여부, Yes , No	|	범주	| 1- 이직, 0- 잔류		|
|	feature	|	Age	|	나이	|	숫자	|		|
|	feature	|	DistanceFromHome	|	집-직장 거리	|	숫자	|	마일	|
|	feature	|	EmployNumber	|	사번	|	숫자	| 	|
|	feature	|	Gender	|	성별	|	범주	| Male, Female		|
|	feature	|	JobSatisfaction	|	직무 만족도	|	범주	|	1 Low, 2 Medium, 3 High, 4 Very High	|
|	feature	|	MaritalStatus	|	결혼상태	|	범주	| Single, Married, Divorced		|
|	feature	|	MonthlyIncome	|	월급	|	숫자	| 달러	|
|	feature	|	OverTime	|	야근여부	|	범주	|	Yes, No	|
|	feature	|	PercentSalaryHike	|	전년대비 급여인상율	|	숫자	|	%	|
|	feature	|	TotalWorkingYears	|	총 경력 연수	|	숫자	|		|

In [ ]:
# 데이터 읽어오기
path = 'https://raw.githubusercontent.com/DA4BAM/dataset/master/Attrition_simple2.CSV'
data = pd.read_csv(path)  

# 상위 5개 확인
data.head(5)

### 5.1.열 이름 변경

- 기존 데이터프레임의 열 이름을 적절히 변경해야 할 경우가 있습니다.
- 또는 집계 결과를 가진 열 이름을 이해하기 쉽게 변경해야 할 경우도 있습니다.

**1) 일부 열 이름 변경**

- **rename()** 메소드를 사용해 변경 전후의 열 이름을 딕셔너리 형태로 나열하는 방법으로 변경합니다.
- **inplace=True** 옵션을 설정해야 변경 사항이 실제 반영이 됩니다.
- 다음과 같이 열 이름을 변경합니다.
    - DistanceFromHome → Distance
    - EmployeeNumber → EmpNo
    - JobSatisfaction → JobSat
    - MonthlyIncome → M_Income
    - PercentSalaryHike → PctSalHike
    - TotalWorkingYears → TotWY

In [ ]:
# rename() 함수로 열 이름 변경
data.rename(columns={'DistanceFromHome' : 'Distance', 
                    'EmployeeNumber' : 'EmpNo',
                    'JobSatisfaction' : 'JobSat',
                    'MonthlyIncome' : 'M_Income',
                    'PercentSalaryHike' : 'PctSalHike',
                    'TotalWorkingYears' : 'TotWY'}, inplace=True)

# 확인
data.head()

**2) 모든 열 이름 변경**

- 모든 열 이름을 변경할 때는 **columns** 속성을 변경합니다.
- 변경이 필요없는 열은 기존 이름을 부여해 변경합니다.

In [ ]:
# 모든 열 이름 변경
data.columns = ['Attr','Age','Dist','EmpNo','Gen','JobSat','Marital','M_Income', 'OT', 'PctSalHike', 'TotWY']

# 확인
data.head()

### 5.2.열 추가

- 새로운 열을 추가하여 기존 데이터에서 계산된 결괏값을 저장해야할 경우가 있습니다.
- 작년 급여액을 계산해서 열을 추가해 봅시다. 
    * 올해 급여 : MonthlyIncome(M_Income)
    * 급여 인상율 : PercentSalaryHike(PctSalHike)
    * 작년 급여 * ( 1 + PctSalHike / 100 ) = M_Income
    * 작년 급여 = M_Income / (( 1 + PctSalHike / 100 )

In [ ]:
# final_amt 열 추가
data['Income_LY'] = data['M_Income'] / (1+data['PctSalHike']/100 )
data['Income_LY'] = round(data['Income_LY'])
# 확인
data.head()

- (참조) insert() 메소드를 사용하면 원하는 위치에 열을 추가할 수 있습니다.

    * 데이터프레임의 칼럼 위치를 너무 신경쓰지 맙시다.^^

<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

[문1] 직무만족도(JobSat) 변수가 어떤 값을 몇 개 갖고 있는지 확인하세요.(.value_counts())

In [ ]:
# 범주값 확인
data['JobSat'].value_counts()

[문2] 1,2를 불만(unsat), 3,4 를 만족(sat)으로 하는 새로운 변수JobSat2를 추가하시오.

np.where를 사용해 봅시다!

In [ ]:
# 열 추가
data['JobSat2'] = np.where(data['JobSat'] <=2, 'unsat', 'sat')

# 확인
data['JobSat2'].value_counts()

[문3] 급여 인상액(Diff_Income)을 추가합시다.

In [ ]:
data['Diff_Income'] = data['M_Income'] - data['Income_LY']
data.head()

### 5.3.열 삭제

- 뭔가를 삭제할 때는 **항상 조심x100** 해야 합니다.

**1) 열 하나 삭제**

- **drop()** 메소드를 사용해 열을 삭제합니다.
- axis=0: 행 삭제(기본 값) 
- axis=1: 열 삭제
- **inplace=True** 옵션을 지정해야 실제로 반영이 됩니다.
    * False : 삭제한 것 처럼 보여줘(조회!)

In [ ]:
# 열 하나 삭제
data.drop('Income_LY', axis=1, inplace=True)

# 확인
data.head()

**2) 여러 열 삭제**

- 삭제할 열을 리스트 형태로 전달해 한 번에 여러 열을 제거할 수 있습니다.

In [ ]:
# 열 두 개 삭제
data.drop(['JobSat2','Diff_Income'], axis=1, inplace=True)

# 확인
data.head()

### 5.4.유익한 기능

- 값을 변경하거나 결괏값을 갖는 열을 추가하는 유익한 기능들을 익혀두면 좋습니다.

**1) map() 메소드**

- **map()** 메소드를 사용하면 범주형 값을 다른 값으로 쉽게 변경 할 수 있습니다.
- 다음 구문은 Gen 변수의 Male, Female을 각각 숫자 1, 0으로 변경합니다.

In [ ]:
# Male -> 1, Female -> 0
data['Gen'] = data['Gen'].map({'Male': 1, 'Female': 0})

# 확인
data.head()

<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

[문1] PctSalHike,TotWY 열을 삭제하시오.

In [ ]:
# 열 두 개 삭제
data.drop(['PctSalHike','TotWY' ], axis=1, inplace=True)

# 확인
data.head()

[문2] Marital 열의 값 Single, Married, Divorce를 각각 숫자 0,1,2로 변경하세요.(.map 사용)

In [ ]:
# Yes -> 1, No -> 0
data['Marital'] = data['Marital'].map({'Single': 0, 'Married': 1, 'Divorce': 2})

# 확인
data.head()

**2) cut() 함수**

- **크기**를 기준으로 범위를 나누어 등급을 지정하고 싶을 때 **cut() 함수**를 사용하면 좋습니다.
- 균등구간분할 : 범위 개수를 지정하면 자동으로 크기를 기준으로 나눕니다.

In [ ]:
# 범위를 3등분해서 등급 구하기
data['M_Income_Group'] = pd.cut(data['M_Income'], 3, labels=['a', 'b', 'c'] )

# 확인
data.head()

In [ ]:
# 범위 확인
data.groupby('M_Income_Group', as_index = False)['M_Income'].agg(['min', 'max'])


- 다음 구문은 아래 범위에 따른 값을 갖는 M_Income_Group2 열을 추가합니다.
  - 10000 이하 → 'a'
  - 10000 초과 15000 이하 → 'b'
  - 15000 초과 → 'c'
- 음의 무한대는 -np.inf, 양의 무한대는 np.inf로 지정합니다.

In [ ]:
# 등급 구하기
bin = [0, 10000, 15000, np.inf]
data['M_Income_Group2'] = pd.cut(data['M_Income'], bins=bin, labels=['a', 'b', 'c'])

# 범위 확인
data.groupby('M_Income_Group2', as_index = False)['M_Income'].agg(['min', 'max'])

### 5.5 종합실습

1) pandas 라이브러리를 불러오세요.

In [ ]:
# 라이브러리 불러오기
import pandas as pd

2) 다음 경로의 파일을 읽어 titanic 데이터프레임을 만드세요.

- 파일 'https://bit.ly/TitanicFile'

**[titanic 데이터 셋 정보]**

- Survived: 생존여부(1=Yes, 0=No)
- Pclass: 객실등급(1=1st, 2=2nd, 3=3rd)
- Sex: 성별(male, female)
- Age: 나이
- Sibsp: 탑승한 형제자매, 배우자 수
- Parch: 탑승한 자녀, 부모 수
- Ticket: 티켓 번호
- Fare: 요금
- Cabin: 객실 번호
- Embarked: 출발한 항구((C=Cherbourg, Q=Queenstown, S=Southampton)

In [ ]:
# 파일 읽어오기
path = 'https://bit.ly/TitanicFile'
titanic = pd.read_csv(path)

3) 상위 5개 행을 확인하세요.

In [ ]:
# 상위 5개 확인
print(titanic.head())

4) 다음 요구사항에 맞게 하나의 코드셀에 순서대로 구문을 작성하고 확인하세요.

- 4-1) PassengerId, Name, Ticket, Cabin 열을 한 번에 삭제하세요.
- 4-2) Sex 열 이름을 Male로 변경하세요.
- 4-3) Male 열 값을 'male'은 1, 'female'은 0으로 변경하세요.
- 4-4) SibSp 열과 Parch 열의 값을 더한 결과를 갖는 Family 열을 추가하세요.
- 4-5) SibSp, Parch 두 열을 삭제하세요.
- 4-6) 결과를 확인하세요.

In [ ]:
# 4-1) PassengerId, Name, Ticket, Cabin 열 삭제
titanic.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1, inplace=True)

# 4-2) 열 이름 변경: Sex --> Male
titanic.rename(columns={'Sex': 'Male'}, inplace=True)

# 4-3) Male 열 값 변경: male --> 1, female --> 0
titanic['Male'] = titanic['Male'].map({'male': 1, 'female':0})

# 4-4) Family = SibSp + Parch
titanic['Family'] = titanic['SibSp'] + titanic['Parch']

# 4-5) SibSp, Parch 열 삭제
titanic.drop(['SibSp', 'Parch'], axis=1, inplace=True)

# 4-6) 확인
print(titanic.head())

5) 나이를 연령대로 구분하고자 합니다. 아래 조건의 값을 갖도록 변수를 추가하세요.
* 0<= <10 : '유아'
* 10<= <20 : 10대
* 20<= <30 : 20대
* 30<= <40 : 30대
* 40<= <50 : 40대
* 50<= <60 : 50대
* 60<= <70 : 60대
* 70<= <80 : 70대
* 80<=     : 80대

> 값의 범위 중 오른쪽(큰값)이 아닌 왼쪽(작은값)이 포함되도록 하려면 pd.cut 함수 옵션에 right = False 라고 지정해야 합니다.  
https://pandas.pydata.org/docs/reference/api/pandas.cut.html

In [ ]:
bin = range(0, 90, 10)
titanic['Age_grp'] = pd.cut(titanic['Age'], bins=bin, right = False)

titanic.head()

## 6.데이터프레임 변경 (2)

- 정확한 데이터 분석을 위해서는 정확한 데이터가 준비되어야 합니다.
- 정확한 데이터 준비를 위해 누락된 데이터나 중복 데이터를 제거하는 전처리 작업이 필요합니다.

In [ ]:
# 라이브러리 불러오기
import pandas as pd

### 6.1.결측치 처리

* 결측치란
    * NA(Not Available) 혹은 NaN(Not A Number)
    * 사용할 수 없는 값
    * 잘못 들어간 값
    * 빈 값

* NaN 조치
    * 중요한(버릴 수 없는) 변수라면,
    * 모델링을 하기전에 반드시 조치해야 합니다.
    * 조치하지 않는다면...
        * NaN 값, 즉 결측치는 정확한 분석을 방해합니다.
        * NaN 값을 만나면 오류가 발생하는 함수도 있습니다.

* NA조치 하는 세 가지 방법
    * ① 제거한다. 
    * ② 채운다
    * ③ 분리한다.

**[airquality 데이터 셋 정보]**

- Ozone: 오존 농도  
- Solar.R: 태양복사량
- Wind: 풍속
- Temp: 기온
- Month: 월
- Day: 일

In [ ]:
# 데이터 읽어오기
path = 'https://raw.githubusercontent.com/DA4BAM/dataset/master/airquality.csv'
air = pd.read_csv(path) 

# 확인
print(air.head())

#### 6.1.1.결측치 찾기

- 결측치 존재 여부를 확인하고 이를 어떻게 처리할 지 방법을 결정해야 합니다.

**1) isnull(), notnull() 메소드 사용**

- **isnull()** 메소드는 결측치면 True, 유효한 값이면 False를 반환합니다.
- **notnull()** 메소드는 결측치면 False, 유효한 값이면 True를 반환합니다.
- isnull() 대신 **isna()**, notnull() 대신 **notna()** 메소드를 사용해도 됩니다.

In [ ]:
# 전체 데이터 중에서 결측치는 True로 표시
air.isna()

In [ ]:
# 전체 데이터 중에서 결측치는 False로 표시
air.notna()

- **sum()** 메소드를 사용해 True 값의 개수, 즉 **열의 결측치 개수**를 확인할 수 있습니다.

In [ ]:
# 열의 결측치 개수 확인
air.isnull().sum()

#### 6.1.2.결측치 제거

- **dropna()** 메소드로 결측치가 있는 열이나 행을 제거할 수 있습니다.
- inplace=True 옵션을 지정해야 해당 데이터프레임에 실제로 반영됩니다.
- axis 옵션으로 행을 제거할 지 열을 제거할 지 지정합니다.
    - axis=0: 행 제거(기본값)
    - axis=1: 열 제거

**1) 어떤 열이든 결측치가 있는 행 제거**

- dropna() 메소드는 기본적으로 어느 열이든 결측치가 있는 행을 제거합니다.

<img src='https://raw.githubusercontent.com/Jangrae/img/master/dropna_01.png' width=300/>

In [ ]:
# 데이터프레임 복사
air_test = air.copy()

# 열의 결측치 개수 확인
air_test.isnull().sum()

In [ ]:
# 결측치가 하나라도 있는 행 제거
air_test.dropna(axis=0, inplace=True)

# 확인
air_test.isna().sum()

**2) 특정 열에 결측치가 있는 행 제거**

- subset 옵션에 열을 지정해 해당 열에 결측치가 있는 행을 제거합니다.

<img src='https://raw.githubusercontent.com/Jangrae/img/master/dropna_02.png' width=300/>

In [ ]:
# 데이터프레임 복사
air_test = air.copy()

# Ozone 열이 결측치인 행 제거
air_test.dropna(subset=['Ozone'], axis=0, inplace=True)

# 확인
air_test.isna().sum()

**3) 결측치가 있는 모든 열 제거**

- axis=1 옵션을 지정해 열을 제거할 수 있습니다.

<img src='https://raw.githubusercontent.com/Jangrae/img/master/dropna_03.png' width=300/>

In [ ]:
# 데이터프레임 복사
air_test = air.copy()

# 결측치가 있는 열 제거
air_test.dropna(axis=1, inplace=True)

# 확인
air_test.isna().sum()

#### 6.1.3.결측치 채우기

- **fillna()** 메소드를 사용해 결측치를 다른 값으로 채울 수 있습니다.

**1) 평균값으로 채우기**

- 결측치가 있는 열의 평균값을 구한 후 결측치를 그 값으로 채웁니다.

In [ ]:
# 데이터프레임 복사
air_test = air.copy()

# Ozone 평균 구하기
mean_Ozone = air_test['Ozone'].mean()

# 결측치를 평균값으로 채우기
air_test['Ozone'].fillna(mean_Ozone, inplace=True)

# 확인
air_test.isna().sum()

**2) 특정 값으로 채우기**

- 모든 결측치, 또는 일부 결측치를 특정 값으로 채웁니다.

In [ ]:
# Solar.R 열의 누락된 값을 0으로 채우기
air_test['Solar.R'].fillna(0, inplace=True)

# 확인
print(air_test.isna().sum())

**3) 직전 행의 값 또는 바로 다음 행의 값으로 채우기**

- 결측치를 바로 앞의 값이나 바로 다음에 나오는 값으로 채웁니다.
- 날짜 또는 시간의 흐름에 따른 값을 갖는 **시계열 데이터**에서 사용할 수 있는 방법입니다.
- **method='ffill'**: 바로 앞의 값으로 변경(Fowared Fill)
- **method='bfill'**: 바로 다음 값으로 변경(Backwared Fill)

<img src='https://github.com/DA4BAM/image/blob/main/ffill,%20bfill.png?raw=true' width=500/>

In [ ]:
# 데이터프레임 복사
air_test = air.copy()

# 결측치 확인
print(air_test.isna().sum())

In [ ]:
air_test.head(7)

In [ ]:
# 이전값으로 채우기
air_test.fillna(method = 'ffill', inplace = True)
air_test.head(7)

**4) 선형보간법으로 채우기**

- **interpolate()** 메소드를 사용해 선형보간법으로 채울 수 있습니다.

<img src='https://github.com/DA4BAM/image/blob/main/interpolate.png?raw=true' width=500/>

In [ ]:
# 데이터프레임 복사
air_test = air.copy()

# 선형보간법으로 채우기
air_test.interpolate(method='linear', inplace=True)

# 확인
air_test.head(7)

* 그 외...추정해서 채우는 방법(KNN Imputation)도 있습니다.

<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

[문1] air를 air_test로 복사해서 결측치를 이후값으로 채운(bfill) 후 채우기 전과 후를 비교해 봅시다.

In [ ]:
air_test = air.copy()

air_test.fillna(method = 'bfill', inplace = True)
air_test.head(7)

### 6.2.가변수(Dummy Variable) 만들기

- 가변수는 일정하게 정해진 범위의 값을 갖는 데이터(범주형 데이터)를 독립된 열로 변환한 것입니다.
- 특히 범주형 문자열 데이터는 머신러닝 알고리즘에 사용하려면 숫자로 변환해야 합니다.
- 가변수를 만드는 과정을 **One-Hot-Encoding** 이라고 부르기도 합니다.
- **get_dummies()** 함수를 사용해서 가변수를 쉽게 만들 수 있습니다.

<img src='https://github.com/DA4BAM/image/blob/main/%EA%B0%80%EB%B3%80%EC%88%98%ED%99%94.png?raw=true' width=800/>

In [ ]:
# 데이터 읽어오기
path = 'https://bit.ly/TipsFile'
tip = pd.read_csv(path)

# 확인
print(tip.head())

#### 6.2.1.범주형 변수 확인

- 범주형 여부를 우선 확인해야 합니다.

In [ ]:
# 열 확인
print(tip.info())

#### 6.2.2.변수 개별 처리

- columns 옵션에 열을 하나 지정해 처리할 수 있습니다.
- 자동으로 원본 열이 제거되고, 열 이름이 prefix로 사용됩니다.
- drop_first=True 옵션을 지정합니다. 
    * 동일한 의미의 변수 하나를 빼는 작업입니다. 
    * 예를들어 성별 변수에서 가변수화를 수행하고 나면, 여자여부, 남자여부 변수 두개가 생성됩니다. 
    * 그런데 여자여부가 1이면 남자여부는 무조건 0이 되어야 합니다. 사실 두 변수가 필요하지 않고 하나를 제외해도 된다는 의미입니다. 
    * 그래서 가변수화 이후 하나의 변수를 제거해주게 됩니다.

In [ ]:
# 가변수화
tip = pd.get_dummies(tip, columns=['sex'], drop_first=True)

# 확인
print(tip.head())

#### 6.2.3.일괄 처리

- columns 옵션에 대상 열을 리스트로 지정해 한 번에 처리합니다.
- 자동으로 열 이름이 prefix로 지정되며 원본 열이 제거됩니다.
- columns 옵션을 지정하지 않으면 문자열 값을 갖는 열 모두를 대상으로 합니다.

In [ ]:
# 모든 범주형 변수를 가변수화
col_dumm = ['smoker', 'day', 'time']
tip = pd.get_dummies(tip, columns=col_dumm, drop_first=True)

# 확인
print(tip.head())

### 6.3 종합실습

1) 다음 요구사항에 맞게 하나의 코드셀에 순서대로 구문을 작성하고 확인하세요. 

- 1-1) pandas 라이브러리를 pd 별칭울 주어 불러오세요.
- 1-2) 다음 경로의 파일을 읽어와 titanic 데이터프레임을 선언하세요.
    - 파일 경로: 'https://bit.ly/TitanicFile' 
- 1-3) PassengerId, Name,Ticket, Cabin 열을 한 번에 제거하세요.

In [ ]:
# 1-1) 라이브러리 불러오기
import pandas as pd

# 1-2) 데이터 읽어오기
path = 'https://bit.ly/TitanicFile'
titanic = pd.read_csv(path)

# 1-3) PassengerId, Name, Ticket, Cabin 열 삭제
titanic.drop(['PassengerId', 'Name','Ticket', 'Cabin'], axis=1, inplace=True)

2) 상위 5개 행을 확인하세요.

In [ ]:
# 상위 5개 확인
print(titanic.head())

3) 다음 요구사항에 맞게 하나의 코드셀에 순서대로 구문을 작성하고 확인하세요. 

- 3-1) Age 열 결측치를 Age 열 평균으로 채우세요.
- 3-2) Embarked 열 결측치를 'S'로 채우세요.
- 3-3) 각 열에 결측치가 남아있는지 확인하세요.

In [ ]:
# 3-1) Age 결측치 평균으로 채우기
age_mean = titanic['Age'].mean()
titanic['Age'].fillna(age_mean,  inplace=True)

# 3-2) Embarked 결측치 'S'로 채우기
titanic['Embarked'].fillna('S', inplace=True)    

# 3-3) 결측치 존재여부 확인
print(titanic.isnull().sum())

4) 다음 요구사항에 맞게 하나의 코드셀에 순서대로 구문을 작성하고 확인하세요. 

- 4-1) groupby 메소드를 사용해 Pclass 별 개수를 집계하여 tmp 데이터프레임으로 선언하세요.
- 4-2) tmp 데이터프레임 열 이름이 Pclass, Count가 되게 변경하세요.

In [ ]:
# 4-1) Pclass 범주값 개수 확인
tmp = titanic.groupby(by='Pclass', as_index=False)['Survived'].count()

# 4-2) 열이름 변경
tmp.columns = ['Pclass', 'Count']

5) Pclass, Sex, Embarked 열을 한 번에 가변수화하세요. 단, 다중공선성 문제가 없도록 범주값 개수보다 하나 적은 수의 열이 만들어지게 하세요.

In [ ]:
# 가변수화
titanic = pd.get_dummies(titanic, columns=['Pclass', 'Sex', 'Embarked'], drop_first=True)

# 확인
print(titanic.head())

## 7.데이터프레임 변경 (3)

In [ ]:
# 라이브러리 불러오기
import pandas as pd

### 7.1. 데이터프레임 합치기(Concat)

- **concat()** 함수를 사용해 두 데이터프레임을 가로 또는 세로로 합칠 수 있습니다.

#### 7.1.1.가로로 합치기

- **axis=1** 옵션을 지정해 가로로 합칠 수 있습니다.
- **행 인덱스 값을 기준으로** 합칩니다!

<img src='https://raw.githubusercontent.com/Jangrae/img/master/concat_ax1.png' width=500, align="left"/>

**1) 데이터 읽어오기**

In [ ]:
# 서울 인구정보 읽어오기 #1
path = 'https://bit.ly/PopH01File'
pop01 = pd.read_csv(path, index_col='year')
pop01.index.name = None

# 확인
print(pop01.head(10))

In [ ]:
# 서울 인구정보 읽어오기 #2
path = 'https://bit.ly/PopH02File'
pop02 = pd.read_csv(path, index_col='year')
pop02.index.name = None
# 확인
print(pop02.head(10))

**2) 데이터프레임 합치기**

- 이제 **concat()** 함수를 사용해 두 데이터프레임을 합쳐봅니다.
- 가로로 합치므로 **axis=1** 옵션을 지정합니다.
- join='outer'는 기본 옵션값이므로 생략이 가능합니다.

In [ ]:
# 모든 헹 합치기
pop = pd.concat([pop01, pop02], join='outer', axis=1)

# 확인
print(pop.head(10))

- pop02 데이터프레임에는 1981~1984년 데이터가 없어 합쳐진 결과에 결측치가 생깁니다.
- join='inner' 옵션을 지정하면 매핑되지 못한 행은 제외됩니다.

In [ ]:
# 모든 헹 합치기
pop = pd.concat([pop01, pop02], join='inner', axis=1)

# 확인
print(pop.head(10))

#### 7.1.2.세로로 합치기


- **axis=0** 옵션을 지정해 세로로 합칠 수 있습니다.(기본값)
- **열 이름을 기준으로** 합칩니다!

<img src='https://raw.githubusercontent.com/Jangrae/img/master/concat_ax0.png' width=450, align="left"/>

**1) 데이터 읽어오기**

In [ ]:
# 서울 인구정보 읽어오기 #1
path = 'https://bit.ly/PopV01File'
pop01 = pd.read_csv(path)

# 확인
print(pop01.head())

In [ ]:
# 서울 인구정보 읽어오기 #2
path = 'https://bit.ly/PopV02File'
pop02 = pd.read_csv(path)

# 확인
print(pop02.head(10))

**2) 데이터프레임 합치기**

- 이제 **concat()** 함수를 사용해 두 데이터프레임을 합쳐봅니다.
- 세로로 합치므로 **axis=0** 옵션을 지정하거나 생략합니다.

In [ ]:
# 모든 헹 합치기
pop = pd.concat([pop01, pop02], axis=0)

# 확인
print(pop)

- 세로로 합해지면 인덱스 값이 중복될 수 있으므로 인덱스를 초기화합니다.

In [ ]:
# 인덱스 초기화
pop.reset_index(drop=True, inplace=True)

# 확인
print(pop)

<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

[문1] 다음의 세 파일을 불러와서 각각 데이터프레임(sales01, sales02, sales03)으로 저장합니다. 
* sales01.csv
* sales02.csv
* sales03.csv

In [ ]:
sales01 = pd.read_csv('sales01.csv')
sales02 = pd.read_csv('sales02.csv')
sales03 = pd.read_csv('sales03.csv')

print(sales01.head())

[문2] 각 데이터프레임에 OrderDate가 있습니다. OrderDate의 범위(min ~ max)를 확인하시오.

In [ ]:
print(sales01['OrderDate'].min(), sales01['OrderDate'].max())
print(sales02['OrderDate'].min(), sales02['OrderDate'].max())
print(sales03['OrderDate'].min(), sales03['OrderDate'].max())

[문3] 세 데이터프레임을 세로로(위, 아래로) 합쳐서 sales 로 저장하시오.

In [ ]:
sales = pd.concat([sales01, sales02, sales03], axis = 0)
sales.head()

### 7.2.데이터프레임 Merge(SQL에서의 Join!)

- **merge()** 함수를 사용, 두 데이터프레임을 **지정한 칼럼** 값을 기준으로 **가로**로(옆으로)병합할 수 있습니다.
    * **지정한 칼럼** : key 라고도 부릅니다. default는 같은 이름 칼럼입니다.
    * merge는 **가로**로 만 병합할 수 있습니다.

<img src='https://raw.githubusercontent.com/Jangrae/img/master/join.png' width=600, align="left"/>

#### 7.2.1.데이터 읽어오기

In [ ]:
# 서울 인구정보 읽어오기 #1
path = 'https://bit.ly/PopH01File'
pop01 = pd.read_csv(path)

# 확인
print(pop01.head(10))

In [ ]:
# 서울 인구정보 읽어오기 #2
path = 'https://bit.ly/PopH02File'
pop02 = pd.read_csv(path)

# 확인
print(pop02.head(10))

#### 7.2.2.inner 조인

- 같은 이름의 열이 있으면 on 옵션을 지정하지 않아도 그 열을 기준으로 조인됩니다.
- 그래도 기준 열을 명시적으로 지정해 주기를 권고합니다.
- how='inner' 옵션은 기본 옵션값이므로 생략할 수 있습니다.

In [ ]:
# 조인
pop = pd.merge(pop01, pop02, on='year', how='inner') 

# 확인
print(pop.head(10))

#### 7.2.3.outer 조인

- how='outer' 옵션을 지정합니다.

In [ ]:
# 조인
pop = pd.merge(pop01, pop02, on='year',  how='outer') 

# 확인
print(pop.head(10))

### 7.3 종합실습1

1) 다음 요구사항에 맞게 하나의 코드셀에 순서대로 구문을 작성하고 확인하세요. 

- 1-1) pandas 라이브러리를 pd 별칭울 주어 불러오세요.
- 1-2) 다음 경로의 파일을 읽어와 air 데이터프레임을 만드세요.

    - 파일 경로: 'https://raw.githubusercontent.com/Jangrae/csv/master/airquality.csv'
    - 단축 경로: 'https://bit.ly/AirQFile'

In [ ]:
# 1-1) 라이브러리 불러오기
import pandas as pd

# 1-2) 파일 읽어오기
path = 'https://bit.ly/AirQFile'
air = pd.read_csv(path)

2) 상위 5개 행을 확인하세요.

In [ ]:
# 상위 5개 확인
print(air.head())

3) 각 열에 결측치가 얼마나 있는지 확인하세요.

In [ ]:
# 결측치 확인
print(air.isnull().sum())

4) 다음 요구사항에 맞게 하나의 코드셀에 순서대로 구문을 작성하고 확인하세요. 

- 4-1) Month, Day 열을 한 번에 삭제하세요.
- 4-2) Ozone, Solar.R 두 열 결측치를 바로 앞의 값으로 채우세요.
- 4-3) 각 열에 결측치가 남아있는지 확인하세요.

In [ ]:
# 4-1) Month, Day 열 삭제
air.drop(['Month', 'Day'], axis=1, inplace=True)

# 4-2) 앞의 값으로 채우기
air['Ozone'].fillna(method='ffill',  inplace=True)
air['Solar.R'].fillna(method='ffill',  inplace=True)

# 4-3) 결측치 존재 여부 확인
print(air.isnull().sum())

5) 다음 요구사항에 맞게 하나의 코드셀에 순서대로 구문을 작성하고 확인하세요.

- 5-1) 기초통계량에서 Temp 열의 25%, 50%, 75% 값을 조회(.describe() 이용)해 q1, q2, q3 변수를 선언하세요.
- 5-2) 아래 범위와 값을 참조해 'a' ~ 'd' 값을 갖는 TempGrp 열을 추가하세요.
    - q1 이하 → 'a'
    - q1 초과 q2 이하 → 'b'
    - q2 초과 q3 이하 → 'c'
    - q3 초과 → 'd'
- 5-3) TempGrp 별 오존 농도를 집계하여 tmp 데이터프레임을 선언하고 조회하시오.

In [ ]:
# 5-1) 사분위수 
q1 = air['Temp'].describe()['25%']
q2 = air['Temp'].describe()['50%']
q3 = air['Temp'].describe()['75%']

# 5-2)
# 라이브러리 불러오기
import numpy as np

# 등급 구하기
bin = [-np.inf, q1, q2, q3, np.inf]
label = ['a', 'b', 'c', 'd']
air['TempGrp'] = pd.cut(air['Temp'], bins=bin, labels=label)

# 5-3) 평균
tmp = air.groupby('TempGrp', as_index=False)['Ozone'].mean()
tmp

### 7.4 종합실습2

1) 다음 요구사항에 맞게 하나의 코드셀에 순서대로 구문을 작성하고 확인하세요.

- 1-1) pandas 라이브러리를 pd 별칭을 주어 불러오세요.
- 1-2) 다음 경로의 파일들을 불러와 **pop01, pop02, pop03** 데이터프레임을 만드세요. 
    - 파일1 경로: 'https://bit.ly/PopH01File'    
    - 파일2 경로: 'https://bit.ly/PopH02File'   
    - 파일3 경로: 'https://bit.ly/PopH03File' 
- 1-3) 세 개의 데이터프레임을 inner 방식으로 **조인(merge)**해 pop 데이터프레임을 만드세요.

In [ ]:
# 1-1) 라이브러리 불러오기
import pandas as pd

# 1-2) pop01 데이터 읽어오기
path = 'https://bit.ly/PopH01File'
pop01 = pd.read_csv(path)

# 1-2) pop02 데이터 읽어오기
path = 'https://bit.ly/PopH02File'
pop02 = pd.read_csv(path)

# 1-2) pop03 데이터 읽어오기
path = 'https://bit.ly/PopH03File'
pop03 = pd.read_csv(path)

# 1-3) 데이터프레임 조인
pop = pd.merge(pop01, pop02, on='year', how='inner')
pop = pd.merge(pop, pop03, on='year', how='inner')

2) pop 데이터프레임 상위 10개 행을 확인하세요.

In [ ]:
# 상위 10개 확인
print(pop.head(10))

3) 다음 요구사항에 맞게 하나의 코드셀에 순서대로 구문을 작성하고 확인하세요.

- 3-1) 다음 공식에 따라 pop 데이터프레임에 k_total, f_total, male, female, total 열을 추가하세요.
    - k_total = k_male + k_female
    - f_total = f_male + f_female
    - male = k_male + f_male
    - female = k_female + f_female
    - total = k_total + f_total
- 3-2) year, total, male, female 열만 추출해 pop_sum 데이터프레임을 선언하세요.
- 3-3) pop_sum 데이터프레임 상위 10개 행을 조회하세요.

In [ ]:
# 3-1) 열 추가
pop['k_total'] = pop['k_male'] + pop['k_female']
pop['f_total'] = pop['f_male'] + pop['f_female']
pop['male'] = pop['k_male'] + pop['f_male']
pop['female'] = pop['k_female'] + pop['f_female']
pop['total'] = pop['k_total'] + pop['f_total']

# 3-2) 대표열 선택
pop_sum = pop[['year', 'total', 'male', 'female']]

# 3-3) 확인
print(pop_sum.head(10))